__Лабораторная работа №2__\
Задание 7

In [2]:
import numpy as np

matrix1 = np.random.randint(1, 11, (2, 3))
matrix2 = np.random.randint(1, 11, (3, 2))

print(matrix1)
print(matrix2)

result = matrix1 @ matrix2

print(result)

[[ 9 10 10]
 [ 4  3  6]]
[[3 2]
 [4 6]
 [4 2]]
[[107  98]
 [ 48  38]]
