__Лабораторная работа №2__

Задание 3

In [3]:
import numpy as np

arr1 = np.random.randint(0, 51, 5)
arr2 = np.random.randint(0, 51, 5)

print(arr1)
print(arr2)

arr_combined = np.vstack((arr1, arr2))
print(arr_combined)

arr_split1, arr_split2 = np.vsplit(arr_combined, 2)
print(arr_split1.flatten())
print(arr_split2.flatten())

[ 4 20 42 36 32]
[18 42 39 50 46]
[[ 4 20 42 36 32]
 [18 42 39 50 46]]
[ 4 20 42 36 32]
[18 42 39 50 46]
