In [8]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = a + b

In [10]:
import numpy as np
arr = np.array([1, 2, 3, 4])

In [16]:
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)

In [19]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)

In [21]:
import numpy as np
arr = np.array([1, 2, 3, 4])
result = arr * 2

In [23]:
>>> import numpy as np
>>> m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
>>> print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [27]:
m[1, 0]

np.int64(5)

In [32]:
>>> m[1, :]

matrix([[5, 6, 7, 8]])

In [33]:
m[:, 2]

matrix([[3],
        [7],
        [5]])

In [35]:
m[1, 2:]

matrix([[7, 8]])

In [36]:
m [0:2, 1]

matrix([[2],
        [6]])

In [37]:
m[0:2, 1:3]

matrix([[2, 3],
        [6, 7]])

In [38]:
cols = [0, 1, 3]
m[:, cols]

matrix([[1, 2, 4],
        [5, 6, 8],
        [9, 1, 7]])

In [42]:
type(m)

numpy.matrix

In [43]:
m = np.array(m)
type(m)

numpy.ndarray

In [60]:
m.shape

(3, 4)

In [50]:
m.max()

np.int64(9)

In [51]:
m.max(axis=1)

array([4, 8, 9])

In [52]:
m.max(axis=0)

array([9, 6, 7, 8])

In [53]:
m.mean()

np.float64(4.833333333333333)

In [54]:
m.mean(axis=1)

array([2.5, 6.5, 5.5])

In [55]:
m.sum()

np.int64(58)

In [56]:
m.sum(axis=0)

array([15,  9, 15, 19])

In [58]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
letters = np.array(['a', 'b', 'c', 'd', 'a', 'e', 'b'])

In [61]:
a = True

In [64]:
b = 5 > 7
print(b)

False


In [65]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [66]:
pos_a = letters == 'a'
pos_a

array([ True, False, False, False,  True, False, False])

In [69]:
less_then_5 = nums < 5
less_then_5

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [70]:
nums[less_then_5]

array([1, 2, 3, 4])

In [72]:
m = np.matrix('1 2 3 4; 5 6 7 8; 9 1 5 7')
print(m)

[[1 2 3 4]
 [5 6 7 8]
 [9 1 5 7]]


In [75]:
mod_m = np.logical_and(m>=3, m<=7)
mod_m

matrix([[False, False,  True,  True],
        [ True,  True,  True, False],
        [False, False,  True,  True]])

In [76]:
m[mod_m]

matrix([[3, 4, 5, 6, 7, 5, 7]])

In [78]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
nums[nums < 5]

array([1, 2, 3, 4])

In [79]:
nums[nums < 5] = 10
print(nums)

[10 10 10 10  5  6  7  8  9 10]


In [80]:
m[m > 7] = 25
print(m)

[[ 1  2  3  4]
 [ 5  6  7 25]
 [25  1  5  7]]


In [81]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
np.arange(5, 12)

array([ 5,  6,  7,  8,  9, 10, 11])

In [83]:
np.arange(1, 5, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [84]:
a = [[1, 2], [3, 4]]
np.matrix(a)

matrix([[1, 2],
        [3, 4]])

In [86]:
b = np.array([[5, 6], [7, 8]])
np.matrix(b)

matrix([[5, 6],
        [7, 8]])

In [87]:
np.matrix('[1, 2; 3, 4]')

matrix([[1, 2],
        [3, 4]])

In [88]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [90]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [91]:
np.ravel(A)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.ravel(A, order='C')

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [94]:
np.ravel(A, order='F')

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [95]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(a % 2 == 0, a * 10, a / 10)

array([ 0. ,  0.1, 20. ,  0.3, 40. ,  0.5, 60. ,  0.7, 80. ,  0.9])

In [96]:
a = np.random.rand(10)
a

array([0.04098468, 0.17987197, 0.06893547, 0.74482089, 0.0028527 ,
       0.63488293, 0.06580173, 0.5465319 , 0.95633198, 0.79119893])

In [97]:
x = np.linspace(0, 1, 5)
x
y = np.linspace(0, 2, 5)
y

array([0. , 0.5, 1. , 1.5, 2. ])

In [98]:
xg, yg = np.meshgrid(x, y)
xg

array([[0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ]])

In [99]:
yg

array([[0. , 0. , 0. , 0. , 0. ],
       [0.5, 0.5, 0.5, 0.5, 0.5],
       [1. , 1. , 1. , 1. , 1. ],
       [1.5, 1.5, 1.5, 1.5, 1.5],
       [2. , 2. , 2. , 2. , 2. ]])

In [100]:
import matplotlib.pyplot as plt
%matplotlib inline