__Лабораторная работа №2__\
Задание 5

In [2]:
import numpy as np

identity_matrix = np.eye(4)
diagonal_matrix = np.diag([5, 10, 15, 20])

sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

print(identity_matrix)
print(diagonal_matrix)
print(sum_identity)
print(sum_diagonal)

if sum_identity > sum_diagonal:
    print("Сумма элементов единичной матрицы больше")
elif sum_identity < sum_diagonal:
    print("Сумма элементов диагональной матрицы больше")
else:
    print("Суммы равны")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
4.0
50
Сумма элементов диагональной матрицы больше
