__Лабораторная работа №2__\
Задание 8

In [1]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 3))

print(matrix)

det = np.linalg.det(matrix)
print(det)

if det != 0:
    inv_matrix = np.linalg.inv(matrix)
    print(inv_matrix)
else:
    print("Матрица вырождена")

[[ 9  9  6]
 [ 1  9  8]
 [ 8 10  7]]
-11.999999999999973
[[ 1.41666667  0.25       -1.5       ]
 [-4.75       -1.25        5.5       ]
 [ 5.16666667  1.5        -6.        ]]
