__Лабораторная работа №2__\
Задание 6

In [2]:
import numpy as np

matrix1 = np.random.randint(1, 21, (3, 3))
matrix2 = np.random.randint(1, 21, (3, 3))

print(matrix1)
print(matrix2)

sum_matrix = matrix1 + matrix2
diff_matrix = matrix1 - matrix2
product_matrix = matrix1 * matrix2

print(sum_matrix)
print(diff_matrix)
print(product_matrix)

[[10 14 15]
 [20 10 14]
 [ 2  3 16]]
[[16 18  9]
 [ 7 11  3]
 [13 16  9]]
[[26 32 24]
 [27 21 17]
 [15 19 25]]
[[ -6  -4   6]
 [ 13  -1  11]
 [-11 -13   7]]
[[160 252 135]
 [140 110  42]
 [ 26  48 144]]
