__Лабораторная работа №2__\
Задание 9

In [2]:
import numpy as np

matrix = np.random.randint(1, 51, (4, 4))

print(matrix)

transposed = matrix.T
print(transposed)

trace = np.trace(matrix)
print(trace)

[[39 12  5 45]
 [16 50 39 39]
 [13 15 13  5]
 [25 16  8 45]]
[[39 16 13 25]
 [12 50 15 16]
 [ 5 39 13  8]
 [45 39  5 45]]
147
