__Лабораторная работа №2__

__Задание 1__ Создание и изменение массивов

In [2]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
arr = arr * 2
arr[arr > 10] = 0
print(arr)

[[ 2  4  6]
 [ 8 10  0]
 [ 0  0  0]]


__Задание 2__ Работа с булевыми функциями

In [1]:
import numpy as np
arr = np.random.randint(1, 101, 20)
mask = arr % 5 == 0
print(arr[mask])
arr[mask] = -1
print(arr)

[10 60 25 85 70]
[57 13 -1 14 -1 79 62 36 69 86 39 -1 -1 83 89 59 -1 42 88 11]


__Задание 3__ Объединение и разбиение массивов

In [2]:
import numpy as np

arr1 = np.random.randint(0, 51, 5)
arr2 = np.random.randint(0, 51, 5)

print(arr1)
print(arr2)

arr_combined = np.vstack((arr1, arr2))
print(arr_combined)

arr_split1, arr_split2 = np.vsplit(arr_combined, 2)
print(arr_split1.flatten())
print(arr_split2.flatten())

[ 5 12 11 24  6]
[18 37 50 39 12]
[[ 5 12 11 24  6]
 [18 37 50 39 12]]
[ 5 12 11 24  6]
[18 37 50 39 12]


__Задание 4__ Генерация и работа с линейными последовательностями

In [4]:
import numpy as np

arr = np.linspace(-10, 10, 50)

total_sum = np.sum(arr)
positive_sum = np.sum(arr[arr > 0])
negative_sum = np.sum(arr[arr < 0])

print(total_sum)
print(positive_sum)
print(negative_sum)

7.105427357601002e-15
127.55102040816328
-127.55102040816327


__Задание 5__ Работа с диагональными и единичными матрицами

In [6]:
import numpy as np

identity_matrix = np.eye(4)
diagonal_matrix = np.diag([5, 10, 15, 20])

sum_identity = np.sum(identity_matrix)
sum_diagonal = np.sum(diagonal_matrix)

print(identity_matrix)
print(diagonal_matrix)
print(sum_identity)
print(sum_diagonal)

if sum_identity > sum_diagonal:
    print("Сумма элементов единичной матрицы больше")
elif sum_identity < sum_diagonal:
    print("Сумма элементов диагональной матрицы больше")
else:
    print("Суммы равны")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 15  0]
 [ 0  0  0 20]]
4.0
50
Сумма элементов диагональной матрицы больше


__Задание 6__ Создание и базовые операции с матрицами

In [15]:
import numpy as np

matrix1 = np.random.randint(1, 21, (3, 3))
matrix2 = np.random.randint(1, 21, (3, 3))

print(matrix1)
print(matrix2)

sum_matrix = matrix1 + matrix2
diff_matrix = matrix1 - matrix2
product_matrix = matrix1 * matrix2

print(sum_matrix)
print(diff_matrix)
print(product_matrix)

[[19 16 10]
 [11 11 12]
 [11  4 14]]
[[20  7 17]
 [ 6 10 11]
 [ 2  9  7]]
[[39 23 27]
 [17 21 23]
 [13 13 21]]
[[-1  9 -7]
 [ 5  1  1]
 [ 9 -5  7]]
[[380 112 170]
 [ 66 110 132]
 [ 22  36  98]]


__Задание 7__ Умножение матриц

In [16]:
import numpy as np

matrix1 = np.random.randint(1, 11, (2, 3))
matrix2 = np.random.randint(1, 11, (3, 2))

print(matrix1)
print(matrix2)

result = matrix1 @ matrix2

print(result)

[[10  8  8]
 [ 6 10  8]]
[[3 7]
 [2 7]
 [6 8]]
[[ 94 190]
 [ 86 176]]


__Задание 8__ Определитель и обратная матрица

In [17]:
import numpy as np

matrix = np.random.randint(1, 11, (3, 3))

print(matrix)

det = np.linalg.det(matrix)
print(det)

if det != 0:
    inv_matrix = np.linalg.inv(matrix)
    print(inv_matrix)
else:
    print("Матрица вырождена")

[[4 1 9]
 [4 3 8]
 [2 5 3]]
6.0
[[-5.16666667  7.         -3.16666667]
 [ 0.66666667 -1.          0.66666667]
 [ 2.33333333 -3.          1.33333333]]


__Задание 9__ транспонирование и след матрицы

In [18]:
import numpy as np

matrix = np.random.randint(1, 51, (4, 4))

print(matrix)

transposed = matrix.T
print(transposed)

trace = np.trace(matrix)
print(trace)

[[43 17 13  5]
 [23  3  9 13]
 [36  8  5 46]
 [21 20 45 37]]
[[43 23 36 21]
 [17  3  8 20]
 [13  9  5 45]
 [ 5 13 46 37]]
88


__Задание 10__ Системы линейных уравнений

In [19]:
import numpy as np

A = np.array([[2, 3, -1],
              [4, -1, 2],
              [-3, 5, 4]])

B = np.array([5, 6, -2])

solution = np.linalg.solve(A, B)

print(solution)

[1.63963964 0.57657658 0.00900901]


__Задание 11__ Индивидульное задание.

__Условие:__ В диете наобходимо велючить 3 продукта: мясо, рыбу и овощи. Они содержат белки, жиры и углеводы в разном количестве.
        В 100 г __мяса__ содержится 20 г белков, 10 г жиров и 5 г углеводов
        В 100 г __рыбы__ 15 г белка, 5 г жиров, 10 г углеводов
        В 100 г __овощей__ 5 г белка, 2 г жиров, 150 г углеводов
        Сколько граммов каждого продукта нужно съесть?
        

In [20]:
import numpy as np
from scipy.optimize import lsq_linear
A = np.array([[20, 15, 5],
              [10, 5, 2],
              [5, 10, 20]])
B = np.array([100, 50, 150])
bounds = (0, np.inf)
result = lsq_linear(A, B, bounds=bounds)
print("Решение (в сотнях граммов):", result.x)
print("Мясо: {:.1f} г".format(result.x[0] * 100))
print("Рыба: {:.1f} г".format(result.x[1] * 100))
print("Овощи: {:.1f} г".format(result.x[2] * 100))

Решение (в сотнях граммов): [3.40590980e+00 2.23398777e-17 6.64498798e+00]
Мясо: 340.6 г
Рыба: 0.0 г
Овощи: 664.5 г
